# Generated by Django 5.2 on 2025-04-04 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmrestOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Armrest Option',
                'verbose_name_plural': 'Armrest Options',
                'db_table': 'products_armrest_option',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BaseDesignOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base Design Option',
                'verbose_name_plural': 'Base Design Options',
                'db_table': 'products_base_design_option',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChairTypeOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chair Type Option',
                'verbose_name_plural': 'Chair Type Options',
                'db_table': 'products_chair_type_option',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColorOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hex_code', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Color Option',
                'verbose_name_plural': 'Color Options',
                'db_table': 'products_color_option',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeatherTypeOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('texture', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leather Type Option',
                'verbose_name_plural': 'Leather Type Options',
                'db_table': 'products_leather_type_option',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Option',
                'verbose_name_plural': 'Material Options',
                'db_table': 'products_material_option',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WheelDesignOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wheel Design Option',
                'verbose_name_plural': 'Wheel Design Options',
                'db_table': 'products_wheel_design_option',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChairTypeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('chair_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_features', to='products.chairtypeoption')),
            ],
            options={
                'verbose_name': 'Chair Type Feature',
                'verbose_name_plural': 'Chair Type Features',
                'db_table': 'products_chair_type_feature',
                'unique_together': {('chair_type', 'feature')},
            },
        ),
    ]
