# Generated by Django 5.1.7 on 2025-04-04 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='customization_options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='is_customizable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('option_type', models.CharField(choices=[('COLOR', 'Color'), ('MATERIAL', 'Material'), ('BASE', 'Base Type'), ('ARMREST', 'Armrest')], max_length=20)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.URLField(blank=True, null=True)),
                ('color_code', models.CharField(blank=True, max_length=7)),
                ('chair_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.chairtype')),
            ],
        ),
    ]
